---
# tasks file for nodejs

- name: Enabling EPEL
  shell: amazon-linux-extras install epel -y

- name: Installing a node and npm 
  yum:
    name:
      - nodejs
      - npm
    enablerepo: epel 
    state: installed
